name: Move card to 'Deployed on Production' column

on:
  push:
    branches: [ main ]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: HiromiShikata/gh-actions-move-all-cards-on-projects@v1.0.1
        with:
          project_name: Microservice Development
          from_column_name: Deployed on Testing
          to_column_name: Deployed on Production
          github_token: ${{ secrets.GH_TOKEN }}