name: Move card to 'Deployed on Testing' column

on:
  pull_request:
    types: [closed]

jobs:
  automate-project-columns:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Microservice Development
          column: Deployed on Testing
          repo-token: ${{ secrets.GH_TOKEN }}
