name: Move card to 'To Do' column

on:
  pull_request:
    types: [converted_to_draft]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: Microservice Development
          column: To Do
          repo-token: ${{ secrets.GH_TOKEN }}
